### ISSUE TITLE
Can't get plex to tune

### ISSUE THREAD

**Issue by jamesdisco** [xiaodoudou/PlexIPTV#11] opened 2018-05-14 18:59 UTC
Hi @xiaodoudou 
Logs are below
[logs.zip](https://github.com/xiaodoudou/PlexIPTV/files/2002158/logs.zip)
you'll see i'm now getting loads of 'Received a device identify request.' errors

**Comment by xiaodoudou** [comment] 2018-05-14 21:21
Hey,
Seems your stream cannot be bufferize for some reasons.
Could you provide me your provider so I can get a trial to check it out?

Cheers

**Comment by jamesdisco** [comment] 2018-05-14 22:00
Here you go 
https://superior-hosting.co.uk/

**Comment by 12nick12** [comment] 2018-05-15 11:18
I can't tune using vaders. Im not using docker. It just keeps on saying preloading.

**Comment by 12nick12** [comment] 2018-05-15 13:25
I was able to get it to work by changing the link to TS

**Comment by jamesdisco** [comment] 2018-05-15 14:36
Tried another provider and having the same issue.
fabiptv.com/

**Comment by rogerb831** [comment] 2018-05-20 16:12
I'm also having the same issue. Any fix?

**Comment by systemlord83** [comment] 2018-05-21 02:43
Hi @xiaodoudou ,

The issue is still there, it does not matter if I use a .ts or .m3u8 file extension on the stream. The direct link works perfectly with VLC.

The docker logs as follows once Plex requests channel:

2018-05-21T02:00:31.541Z plexiptv:index:verbose 2018/05/21 02:00:31.5410 🔭 proxy Receive a proxy for: 431
2018-05-21T02:00:31.545Z plexiptv:preloader:verbose 2018/05/21 02:00:31.5450 🔭 preload Create preload for: http://172.17.0.15:1234/channel/431
2018-05-21T02:00:31.546Z plexiptv:worker:verbose 2018/05/21 02:00:31.5460 🔭 subscribe Subscribe to: http://172.17.0.15:1234/channel/431
2018-05-21T02:00:31.545Z plexiptv:worker:verbose 2018/05/21 02:00:31.5440 🔭 requestFactory Preloading: http://172.17.0.15:1234/channel/431 (http://tv.REDACTED.com:80/live/REDACTED/REDACTED/14658.m3u8)
2018-05-21T02:31:13.754Z plexiptv:worker:verbose 2018/05/21 02:31:13.7540 🔭 myRequest.once Renew preloading: undefined,
2018-05-21T02:31:13.754Z plexiptv:worker:verbose 2018/05/21 02:31:13.7540 🔭 requestFactory Preloading: http://172.17.0.15:1234/channel/431 (http://tv.REDACTED.com:80/live/REDACTED/REDACTED/14658.m3u8),
2018-05-21T02:31:14.126Z plexiptv:worker:verbose 2018/05/21 02:31:14.1260 🔭 myRequest.once Renew preloading: undefined,
2018-05-21T02:31:14.126Z plexiptv:worker:verbose 2018/05/21 02:31:14.1260 🔭 requestFactory Preloading: http://172.17.0.15:1234/channel/431 (http://tv.REDACTED.com:80/live/REDACTED/REDACTED/14658.m3u8),
2018-05-21T02:31:14.144Z plexiptv:worker:verbose 2018/05/21 02:31:14.1440 🔭 unsubscribe Unsubscribe to: http://172.17.0.15:1234/channel/431,
2018-05-21T02:31:14.144Z plexiptv:worker:verbose 2018/05/21 02:31:14.1440 🔭 unsubscribe No more subscribers.,
2018-05-21T02:31:14.144Z plexiptv:worker:verbose 2018/05/21 02:31:14.1440 🔭 end End of: http://172.17.0.15:1234/channel/431,

Plex will error 'Playback Error' 'Unable to tune channel'

Everything else seems to be working fine, its finding my config, my filters, and Plex does not report that the DVR is offline etc.

Thanks in advanced
-SystemLord

**Comment by silkyclouds** [comment] 2018-06-12 15:12
I checked my own logs and I do have the exact same problem. I get a very high load of "myRequest.once Renew preloading: undefined" messages when I try to tune to a channel. 

which then ends-up with something like : 

"unsubscribe Unsubscribe to: http://127.0.0.1:12345/channel/80039"

and : 

"unsubscribe No more subscribers."

and finally : 

"end End of: http://127.0.0.1:12345/channel/80039"

**Comment by silkyclouds** [comment] 2018-06-12 15:28
is there any advancement on this ? would be nice to be able to tune in the channels to be honest ;)

**Comment by 12nick12** [comment] 2018-06-12 15:40
I don't think the person has done much of anything recently. I'm unable to
tune on mobile. It sucks because the features are better than telly.

**Comment by silkyclouds** [comment] 2018-06-13 08:13
I didn't try Telly, but I did use headendtv + a proxy to link it to plex in the past, and indeed, this new tool is way easier to configure. But as I said, ending up with a nice looking dvr and epg, but without any way to tune in, is quite useless... I hope the dev will investigate this soon. ;)

**Comment by gdbytes** [comment] 2018-06-16 22:43
The same issue, It doesn't seem to want to return any channels at all. I tried with Telly and it worked instantly.

**Comment by silkyclouds** [comment] 2018-06-17 16:14
OK guys I'm back with some feedback as I had some time to try out telly today. Issue is the same. 
Unable to tune in to channel. 
The telly log displays : "[debug] Redirecting to: http:linktothechan" and plex fails to tune in. 

So we can state plex IPTV can't be incriminated here.

**Comment by gdbytes** [comment] 2018-06-17 18:00
Telly worked for me using m3u and ts output.
Could not get it working in PlexIPTV

**Comment by silkyclouds** [comment] 2018-06-17 18:14
well, my line is complying to this : 

type=m3u_plus&output=ts

unfortunately, not working...so the  mystery remains ! :) 

Unlucky me, I can't get my streams to load either with plexiptv or telly...

**Comment by xiaodoudou** [comment] 2018-06-22 06:16
Duplicate of https://github.com/xiaodoudou/PlexIPTV/issues/8
if your provider is based on xtream code api, should work properly if not, neither PlexIPTV or Telly can make it works.

The reason is we need to work on a preprocess approach to re-encode the IPTV stream to MPEG2 TS which is what Plex is expecting.

**Closed by xiaodoudou** 2018-06-22 06:16 UTC
Labels: bug
